# Used for deployment to a server where we are getting images from Docker Hub
# Overlay ontop of base config with:
#    $ export IMAGE_TEST="v2022-05-20.ABCD1234"
#    $ docker compose -f docker-compose.yml -f docker-compose.deploy.yml up -d
# Set IMAGE_TAG to the image desired, such as:
#     dev
#     staging
#     vYYYY-MM-DD.SHA
version: "3.9"
services:
  fluentbit:
    container_name: cbr_fluentbit
    image: fluent/fluent-bit:2.0.5
    volumes:
      - ./fluentbit/config:/fluent-bit/etc
      - fluentbit_logs_output:/output
      - django_logs:/logs/django:ro
      - fluentbit_logs_db:/persist
      - caddy_logs:/logs/caddy:ro
    ports:
      - "24224:24224"
    environment:
      AWS_LOGGING_REGION: ${AWS_LOGGING_REGION}
      GRAFANA_API_KEY: ${GRAFANA_API_KEY}
      PROMETHEUS_API_KEY: ${GRAFANA_API_KEY}
      # Used in staging/prod environment
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-${ENV:-local}.conf"]
  django:
    image: drbfraser/hopehealthaction_cbr_backend:$IMAGE_TAG
    build:
      dockerfile: Dockerfile.deploy
    restart: always
    command: gunicorn -k eventlet --workers 1 cbr.wsgi --bind 0:8000
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - django_logs:/var/log
      - django_uploads:/uploads/
  postgres:
    restart: always
    logging:
      driver: fluentd
      options:
          tag: docker.{{.Name}}.{{.ID}}
          fluentd-async: "true"
          fluentd-address: tcp://localhost:24224
    volumes:
      - cbr_postgres_data:/var/lib/postgresql/data
  caddy:
    container_name: cbr_caddy
    image: drbfraser/hopehealthaction_cbr_revproxy_frontend:$IMAGE_TAG
    build:
      context: .
      dockerfile: caddy/Dockerfile
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - API_HOSTNAME=cbr_django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_logs:/var/log

volumes:
  cbr_postgres_data:
  django_logs:
  django_uploads:
  fluentbit_logs_db:
  caddy_logs:
  fluentbit_logs_output:
