version: "3.7"
services:
  django:
    restart: always
    command: gunicorn -k eventlet --workers 1 cbr.wsgi --bind 0:8000
    user: ${GITLAB_RUNNER_UID_GID}
    environment:
      - DOMAIN=${DOMAIN}
  postgres:
    restart: always
  caddy:
    container_name: cbr_caddy
    image: caddy:2.4.6
    restart: always
    volumes:
      - ./caddy:/etc/caddy
      - ./web/build:/var/www
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - API_HOSTNAME=cbr_django
