version: "3.7"
services:
  django:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - LISTEN_PORT=8000
      - DEBUG=yes
    volumes:
      - ./server:/code
  postgres:
    ports:
      - "5432:5432"
