services:
    django:
        command: uvicorn cbr.asgi:application --host 0.0.0.0 --port 8000 --reload
        ports:
            - "8000:8000"
        environment:
            - DEBUG=yes
        volumes:
            - ./server:/code
    postgres:
        ports:
            - "5432:5432"
