version: "3.9"
services:
  fluentbit:
    container_name: cbr_fluentbit
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluentbit/config:/fluent-bit/etc
      - ./fluentbit/config/fluent-development.conf:/fluent-bit/etc/fluent-bit.conf
      - fluentbit_logs_output:/output
      - fluentbit_logs_db:/persist
      - django_logs:/logs/django:ro
      - caddy_logs:/logs/caddy:ro
    ports:
      - "24224:24224"
    environment:
      GRAFANA_API_KEY: ${GRAFANA_API_KEY}
      PROMETHEUS_API_KEY: ${GRAFANA_API_KEY}
      # Used in staging/prod environment
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  django:
    container_name: cbr_django
    build:
      context: ./server
    environment:
      - POSTGRES_HOST=cbr_postgres
      - POSTGRES_DB=cbr
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    logging:
      driver: fluentd
      options:
          tag: docker.{{.Name}}.{{.ID}}
          fluentd-async: "true"
          fluentd-address: tcp://localhost:24224
    depends_on:
      - postgres
    volumes:
      - django_logs:/var/log
  postgres:
    container_name: cbr_postgres
    image: postgres:13.1-alpine
    logging:
      driver: fluentd
      options:
          tag: docker.{{.Name}}.{{.ID}}
          fluentd-async: "true"
          fluentd-address: tcp://localhost:24224
    environment:
      - POSTGRES_DB=cbr
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - cbr_postgres_data:/var/lib/postgresql/data

volumes:
  cbr_postgres_data:
  django_logs:
  caddy_logs:
  fluentbit_logs_db:
  fluentbit_logs_output: