version: "3.7"
services:
    django:
        restart: always
        command: gunicorn cbr.wsgi --bind 0:8000
    postgres:
        restart: always
    caddy:
        container_name: cbr_caddy
        image: caddy:2.0.0
        restart: always
        volumes:
            - ./caddy:/etc/caddy
            - ./client/build:/var/www
            - cbr_caddy:/root/.caddy
        ports:
            - 80:80
            - 443:443
        environment: 
            CADDY_DOMAIN: ${CADDY_DOMAIN}

volumes:
    cbr_caddy: