# Copy the translations from the source folder to the locales folders for common
# 
# Run via PowerShell (in project root)
#   .\locales\replicate_translations.ps1
# (Can be run from any directory)

# Get the source code folder of these files
$sourceCodeFolder = Split-Path -Parent $MyInvocation.MyCommand.Definition

# Validate source files are correct JSON
$sourceFiles = Get-ChildItem -Path "$sourceCodeFolder\*.json"
foreach ($sourceFile in $sourceFiles) {
    # Supports older PowenShell versions
    # try {
    #     Get-Content $sourceFile.FullName | ConvertFrom-Json | Out-Null
    # } catch {
    #     Write-Host "ERROR: $sourceFile is not valid JSON"
    #     exit 1
    # }

    # Supports newer (PowerSHell version 6+) versions
    $text = Get-Content $sourceFile.FullName -Raw
    if ($text | Test-Json) {
        $powershellRepresentation = ConvertFrom-Json $text -ErrorAction Stop;
    } else {
        Write-Host "Provided text is not a valid JSON string";
    }

}

# Set array of target folders
$targetFolders = @(
    "$sourceCodeFolder\..\common\src\locales"
)

# For each target folder
foreach ($targetFolder in $targetFolders) {
    # Copy the translations
    Copy-Item -Path "$sourceCodeFolder\*.json" -Destination $targetFolder -Force

    # Change first line of each copied file to warn not to edit.
    Get-ChildItem -Path "$targetFolder\*.json" | ForEach-Object {
        # Get the first line
        $firstLine = Get-Content $_.FullName -TotalCount 1

        # Create a temporary file
        $tempFile = "$($_.FullName).tmp"

        # Write the warning to the temporary file
        Set-Content -Path $tempFile -Value $firstLine
        Add-Content -Path $tempFile -Value '    "COPIED_WARNING": "DO NOT EDIT THIS FILE; it is copied by replicate_translations script",'
        # Write rest of the file to the temporary file
        Get-Content $_.FullName | Select-Object -Skip 1 | Add-Content -Path $tempFile

        # Move the temporary file to the original file
        Move-Item -Path $tempFile -Destination $_.FullName -Force
    }

    # Add warning to output folder
    Set-Content -Path $targetFolder\ATTENTION-DO_NOT_EDIT.md -Value "DO NOT EDIT THESE FILES; they are copied by replicate_translations script"
}