@REM Copy the translations from the source code to the locales folder

@REM Set the source code folder
set SOURCE_CODE_FOLDER=.

@REM Set array of target folders
set TARGET_FOLDERS=..\mobile\src\locales ..\common\src\locales ..\web\src\locales

@REM For each target folder
for %%F in (%TARGET_FOLDERS%) do (
    @REM Copy the translations
    echo xcopy /Y /I "%SOURCE_CODE_FOLDER%\*.json" "%%F\"

    @REM Create file notifying it's just a copy
    echo "This file is automatically generated by the `translation_copy` script. Do not edit it manually." > "%%F\DO_NOT_EDIT_THESE_JSON_FILES.txt"
)