# Generated by Django 3.1.7 on 2021-03-02 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="purpose",
        ),
        migrations.AddField(
            model_name="visit",
            name="educat_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="nutrit_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="health_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="social_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="improvement",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="improvements",
                to="cbr_api.visit",
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="cbr_api.visit",
            ),
        ),
    ]
