# Generated by Django 3.1.6 on 2021-02-04 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbr_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('risk_type', models.CharField(choices=[('HEALTH', 'Health'), ('SOCIAL', 'Social'), ('EDUCAT', 'Education')], max_length=6)),
                ('risk_level', models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High'), ('CR', 'Critical')], max_length=2)),
                ('requires', models.TextField()),
                ('goals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='caregiver_contact',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='education_goal_met',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='education_goal_outcome',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='education_risk',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='health_goal_met',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='health_goal_outcome',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='health_risk',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='social_goal_met',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='social_goal_outcome',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='social_risk',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visit',
            name='caregiver_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visit',
            name='caregiver_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_village',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disability',
            name='disability_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='improvement_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='improvement_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_village',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='usercbr',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cbr_api.zone'),
        ),
        migrations.AddField(
            model_name='clientrisk',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbr_api.client'),
        ),
    ]
