# Generated by Django 3.1.7 on 2021-03-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0002_auto_20210301_2333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="cbr_api.client",
            ),
        ),
    ]
