# Generated by Django 3.1.6 on 2021-02-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0002_auto_20210207_0158"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="created_by_user_id",
            new_name="created_by_user",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="register_date",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="clientrisk",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="usercbr",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="visit",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="visit",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="client",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="visit_id",
        ),
        migrations.AddField(
            model_name="client",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
    ]
