# Generated by Django 3.1.6 on 2021-02-05 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0002_auto_20210204_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='current_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='current_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='current_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='current_village',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='current_zone',
            new_name='zone',
        ),
        migrations.RenameField(
            model_name='clientrisk',
            old_name='goals',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='clientrisk',
            old_name='requires',
            new_name='requirement',
        ),
        migrations.RenameField(
            model_name='improvement',
            old_name='improvement_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='improvement',
            old_name='improvement_type',
            new_name='provided',
        ),
        migrations.RenameField(
            model_name='usercbr',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_village',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_zone',
            new_name='zone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='caregiver_email',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='caregiver_phone',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='caregiver_present',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_picture',
        ),
        migrations.AddField(
            model_name='client',
            name='caregiver_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='caregiver_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='caregiver_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='client',
            name='caregiver_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='improvement',
            name='risk_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('SOCIAL', 'Social'), ('EDUCAT', 'Education')], default='HEALTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clientrisk',
            name='risk_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('SOCIAL', 'Social'), ('EDUCAT', 'Education')], default='HEALTH', max_length=6),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('HEALTH', 'Health'), ('SOCIAL', 'Social'), ('EDUCAT', 'Education')], default='HEALTH', max_length=6)),
                ('goal_met', models.CharField(choices=[('CAN', 'Cancelled'), ('GO', 'Ongoing'), ('CON', 'Concluded')], max_length=3)),
                ('outcome', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbr_api.visit')),
            ],
        ),
    ]
