# Generated by Django 3.1.6 on 2021-02-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0003_auto_20210210_2109"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="educat_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="health_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="social_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="clientrisk",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
    ]
