# Generated by Django 3.1.6 on 2021-03-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0002_client_full_name"),
        ("cbr_api", "0003_auto_20210302_0103"),
    ]

    operations = []
