# Generated by Django 3.1.6 on 2021-02-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0004_auto_20210213_2356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientrisk",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risks",
                to="cbr_api.client",
            ),
        ),
    ]
