# Generated by Django 3.1.6 on 2021-03-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0004_merge_20210302_2235"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="caregiver_name",
            field=models.CharField(blank=True, max_length=101),
        ),
    ]
