# Generated by Django 3.1.6 on 2021-03-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0005_client_caregiver_name"),
        ("cbr_api", "0005_merge_20210303_1938"),
    ]

    operations = []
