# Generated by Django 3.1.6 on 2021-03-10 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0006_merge_20210306_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_referred', models.BigIntegerField()),
                ('date_resolved', models.BigIntegerField()),
                ('resolved', models.BooleanField(default=False)),
                ('outcome', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('wheelchair', models.BooleanField(default=False)),
                ('wheelchair_experience', models.CharField(choices=[('BAS', 'Basic'), ('INT', 'Intermediate')], max_length=3)),
                ('hip_width', models.IntegerField()),
                ('wheelchair_owned', models.BooleanField(default=False)),
                ('wheelchair_repairable', models.BooleanField(default=False)),
                ('physiotherapy', models.BooleanField(default=False)),
                ('condition', models.CharField(max_length=100)),
                ('prosthetic', models.BooleanField(default=False)),
                ('prosthetic_injury_location', models.CharField(choices=[('BEL', 'Below'), ('ABO', 'Above')], max_length=3)),
                ('orthotic', models.BooleanField(default=False)),
                ('orthotic_injury_location', models.CharField(choices=[('BEL', 'Below'), ('ABO', 'Above')], max_length=3)),
                ('services_other', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='cbr_api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
