# Generated by Django 3.1.6 on 2021-03-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0007_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="date_resolved",
            field=models.BigIntegerField(default=0),
        ),
    ]
