# Generated by Django 3.1.6 on 2021-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0009_usercbr_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="condition",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="hip_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="referral",
            name="orthotic_injury_location",
            field=models.CharField(
                blank=True, choices=[("BEL", "Below"), ("ABO", "Above")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="prosthetic_injury_location",
            field=models.CharField(
                blank=True, choices=[("BEL", "Below"), ("ABO", "Above")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="services_other",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="wheelchair_experience",
            field=models.CharField(
                blank=True,
                choices=[("BAS", "Basic"), ("INT", "Intermediate")],
                max_length=3,
            ),
        ),
    ]
