# Generated by Django 3.1.6 on 2021-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0010_auto_20210330_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='hip_width',
            field=models.IntegerField(default=0),
        ),
    ]
