# Generated by Django 3.1.6 on 2021-04-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0010_client_last_visit_date"),
        ("cbr_api", "0010_auto_20210330_0050"),
    ]

    operations = []
