# Generated by Django 3.1.6 on 2021-04-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0011_merge_20210331_2255"),
        ("cbr_api", "0010_auto_20210330_1855"),
    ]

    operations = []
