# Generated by Django 3.1.7 on 2021-04-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0012_merge_20210402_2242"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="other_disability",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
