# Generated by Django 3.1.7 on 2021-04-08 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0013_baselinesurvey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselinesurvey",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baseline_surveys",
                to="cbr_api.client",
            ),
        ),
    ]
