# Generated by Django 3.1.6 on 2021-04-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0013_client_last_referral_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="last_referral_date",
        ),
    ]
