# Generated by Django 3.1.7 on 2021-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0013_client_other_disability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="disability",
            field=models.ManyToManyField(blank=True, to="cbr_api.Disability"),
        ),
    ]
