# Generated by Django 3.1.7 on 2021-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0014_baselinesurvey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselinesurvey",
            name="empowerment_organization",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinesurvey",
            name="food_enough_for_child",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Malnourished"),
                    ("U", "Undernourished"),
                    ("W", "Well-nourished"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="baselinesurvey",
            name="health_assistive_device_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WC", "Wheelchair"),
                    ("PR", "Prosthetic"),
                    ("OR", "Orthotic"),
                    ("CR", "Crutch"),
                    ("WS", "Walking Stick"),
                    ("HA", "Hearing Aid"),
                    ("GL", "Glasses"),
                    ("SF", "Standing Frame"),
                    ("CS", "Corner Seat"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="baselinesurvey",
            name="school_not_attend_reason",
            field=models.CharField(
                blank=True,
                choices=[("LF", "Lack Funding"), ("D", "Disability"), ("O", "Other")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="baselinesurvey",
            name="work_status",
            field=models.CharField(
                blank=True,
                choices=[("EMPL", "Employed"), ("SEMPL", "Self-Employed")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="baselinesurvey",
            name="work_what",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
