# Generated by Django 3.1.7 on 2021-04-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0015_auto_20210407_1833"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baselinesurvey",
            old_name="school_currently",
            new_name="school_currently_attend",
        ),
        migrations.RenameField(
            model_name="baselinesurvey",
            old_name="school_ever_in",
            new_name="school_ever_attend",
        ),
        migrations.RenameField(
            model_name="baselinesurvey",
            old_name="school_why_not",
            new_name="school_not_attend_reason",
        ),
        migrations.RenameField(
            model_name="baselinesurvey",
            old_name="school_want",
            new_name="school_want_attend",
        ),
    ]
