# Generated by Django 3.2.5 on 2021-07-27 03:56
import time

from django.db import migrations, models


def set_modified_date(app_registry, schema_editor):
    current_date = int(time.time())
    Client = app_registry.get_model("cbr_api", "Client")
    Client.objects.all().update(modified_date=current_date)


class Migration(migrations.Migration):
    dependencies = [
        ("cbr_api", "0016_alter_client_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="modified_date",
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunPython(set_modified_date),
        migrations.AlterField(
            model_name="client",
            name="modified_date",
            field=models.BigIntegerField(),
        ),
    ]
