# Generated by Django 3.2.5 on 2021-07-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0017_client_modified_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="caregiver_picture",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="picture",
        ),
    ]
