# Generated by Django 3.2.5 on 2021-07-27 08:30

import cbr_api.models
import cbr_api.storage
import cbr_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0018_auto_20210727_0011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="picture",
            field=models.ImageField(
                blank=True,
                storage=cbr_api.storage.OverwriteStorage(),
                upload_to=cbr_api.models.Client.rename_file,
                validators=[cbr_api.validators.FileSizeValidator(5242880)],
            ),
        ),
    ]
