# Generated by Django 3.2.7 on 2021-09-27 16:07

import cbr_api.models
import cbr_api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0020_auto_20210728_2053"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="picture",
            field=models.ImageField(
                blank=True,
                storage=cbr_api.storage.OverwriteStorage(),
                upload_to=cbr_api.models.Referral.rename_file,
            ),
        ),
    ]
