# Generated by Django 3.2.7 on 2021-10-02 01:37

import cbr_api.models
import cbr_api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0021_referral_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="picture",
            field=models.ImageField(
                blank=True,
                storage=cbr_api.storage.OverwriteStorage(),
                upload_to=cbr_api.models.Client.rename_file,
            ),
        ),
    ]
