# Generated by Django 3.2.8 on 2021-11-08 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0022_alter_client_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=9)),
                ('subject', models.CharField(max_length=50)),
                ('alert_message', models.CharField(max_length=2000)),
                ('created_date', models.BigIntegerField(default=time.time, verbose_name='date created')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
