# Generated by Django 3.2.8 on 2021-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0022_alter_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercbr',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
