# Generated by Django 3.2.8 on 2021-10-30 18:40

import cbr_api.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0023_alter_usercbr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercbr',
            name='created_date',
        ),
        migrations.AddField(
            model_name='usercbr',
            name='created_at',
            field=models.BigIntegerField(default=cbr_api.util.current_milli_time, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='usercbr',
            name='updated_at',
            field=models.BigIntegerField(default=0, verbose_name='date created'),
        ),
    ]
