# Generated by Django 3.2.8 on 2021-11-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0025_auto_20211101_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
