# Generated by Django 3.2.9 on 2021-11-07 05:14

import cbr_api.models
import cbr_api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0026_auto_20211104_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cbr_api.storage.OverwriteStorage(),
                upload_to=cbr_api.models.Client.rename_file,
            ),
        ),
    ]
