# Generated by Django 3.2.9 on 2021-11-13 03:51

import cbr_api.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0029_auto_20211109_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="server_created_at",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientrisk",
            name="server_created_at",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="improvement",
            name="server_created_at",
            field=models.BigIntegerField(default=cbr_api.util.current_milli_time),
        ),
        migrations.AddField(
            model_name="outcome",
            name="server_created_at",
            field=models.BigIntegerField(default=cbr_api.util.current_milli_time),
        ),
        migrations.AddField(
            model_name="usercbr",
            name="server_created_at",
            field=models.BigIntegerField(default=cbr_api.util.current_milli_time),
        ),
        migrations.AddField(
            model_name="visit",
            name="server_created_at",
            field=models.BigIntegerField(default=0),
        ),
    ]
