# Generated by Django 3.2.9 on 2021-11-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0024_alter_alert_priority"),
        ("cbr_api", "0030_auto_20211112_1951"),
    ]

    operations = []
