# Generated by Django 3.2.9 on 2021-11-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0031_merge_0027_auto_20211113_0103_0030_auto_20211112_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baselinesurvey',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='baselinesurvey',
            old_name='user',
            new_name='user_id',
        ),
    ]
