# Generated by Django 3.2.9 on 2021-11-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0027_auto_20211104_2231"),
        ("cbr_api", "0034_remove_baselinesurvey_updated_at"),
    ]

    operations = []
