# Generated by Django 3.2.9 on 2021-11-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0034_remove_baselinesurvey_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baselinesurvey",
            name="created_at",
        ),
    ]
