# Generated by Django 3.2.9 on 2021-11-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0031_merge_20211115_1933"),
        ("cbr_api", "0035_remove_baselinesurvey_created_at"),
    ]

    operations = []
