# Generated by Django 3.2.9 on 2021-11-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0035_remove_baselinesurvey_created_at"),
        ("cbr_api", "0037_alter_referral_picture"),
    ]

    operations = []
