# Generated by Django 3.2.9 on 2021-11-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0036_merge_20211115_1951"),
        ("cbr_api", "0037_alter_referral_picture"),
    ]

    operations = []
