# Generated by Django 3.2.9 on 2021-11-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0039_remove_referral_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="unread_by_users",
            field=models.TextField(blank=True),
        ),
    ]
