# Generated by Django 3.2.9 on 2022-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0042_auto_20211128_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nutrit_risk_level',
            field=models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High'), ('CR', 'Critical')], default='LO', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='nutrit_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientrisk',
            name='risk_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('SOCIAL', 'Social'), ('EDUCAT', 'Education'), ('NUTRIT', 'Nutrition')], default='HEALTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='risk_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('SOCIAL', 'Social'), ('EDUCAT', 'Education'), ('NUTRIT', 'Nutrition')], default='HEALTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='risk_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('SOCIAL', 'Social'), ('EDUCAT', 'Education'), ('NUTRIT', 'Nutrition')], default='HEALTH', max_length=6),
        ),
    ]
