# Generated by Django 3.2.9 on 2021-12-06 19:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0042_auto_20211128_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="unread_by_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True), default=list, size=None
            ),
        ),
    ]
