# Generated by Django 3.2.9 on 2022-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0042_auto_20211128_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nutrit_timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
