# Generated by Django 3.2.9 on 2022-03-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0043_client_nutrit_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nutrit_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
    ]
