# Generated by Django 3.2.9 on 2022-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0044_client_nutrit_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='nutrit_visit',
            field=models.BooleanField(default=False),
        ),
    ]
