# Generated by Django 3.2.9 on 2022-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0045_visit_nutrit_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="agriculture_livelihood_program_enrollment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="referral",
            name="emergency_food_aid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="referral",
            name="hha_nutrition_and_agriculture_project",
            field=models.BooleanField(default=False),
        ),
    ]
