# Generated by Django 4.0 on 2023-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0048_alert_server_created_at_alert_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
