# Generated by Django 4.0 on 2023-05-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_api', '0050_alter_referral_orthotic_injury_location_and_more'),
        ('cbr_api', '0050_alter_referral_orthotic_injury_location_and_more 2'),
    ]

    operations = [
    ]
