# Generated by Django 4.0 on 2023-05-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0052_client_mental_risk_level_client_mental_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="mental_visit",
            field=models.BooleanField(default=False),
        ),
    ]
