# Generated by Django 4.0 on 2023-05-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0053_visit_mental_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselinesurvey",
            name="health_have_mental_condition",
            field=models.BooleanField(default=False),
        ),
    ]
