# Generated by Django 4.1.10 on 2023-08-15 06:55

from django.db import migrations
import uuid
import time


def add_mental_risk_type(apps, schema_editor):
    ClientRisk = apps.get_model("cbr_api", "ClientRisk")
    timestamp = int(time.time() * 1000)

    client_ids_without_mental = (
        ClientRisk.objects.exclude(risk_type="MENTAL")
        .values_list("client_id_id", flat=True)
        .distinct()
    )

    # For each client, create a new record with risk_type as "MENTAL", requirement as "No requirement" and goal as "No goal"
    for client_id in client_ids_without_mental:
        ClientRisk.objects.create(
            id=uuid.uuid4(),
            client_id_id=client_id,
            risk_type="MENTAL",
            requirement="Client not asked about mental health.",
            timestamp=timestamp,
            server_created_at=timestamp,
            goal="Client not asked about mental health.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0056_alter_clientrisk_goal_alter_clientrisk_requirement"),
    ]

    operations = [
        migrations.RunPython(add_mental_risk_type),
    ]
