# Generated by Django 4.1.10 on 2025-03-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0057_auto_20230814_2355"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrisk",
            name="end_date",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientrisk",
            name="goal_name",
            field=models.TextField(default="No goal set"),
        ),
        migrations.AddField(
            model_name="clientrisk",
            name="goal_status",
            field=models.CharField(
                choices=[
                    ("CAN", "Cancelled"),
                    ("GO", "Ongoing"),
                    ("CON", "Concluded"),
                    ("NS", "Not Set"),
                ],
                default="NS",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="clientrisk",
            name="start_date",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="goal_met",
            field=models.CharField(
                choices=[
                    ("CAN", "Cancelled"),
                    ("GO", "Ongoing"),
                    ("CON", "Concluded"),
                    ("NS", "Not Set"),
                ],
                max_length=3,
            ),
        ),
    ]
