# Generated by Django 4.1.10 on 2025-03-24 04:28

from django.db import migrations


def update_goal_name_to_goal(apps, schema_editor):
    ClientRisk = apps.get_model("cbr_api", "ClientRisk")

    for risk in ClientRisk.objects.all():
        risk.goal_name = risk.goal
        risk.save()


def reverse_migration(apps, schema_editor):
    ClientRisk = apps.get_model("cbr_api", "ClientRisk")
    ClientRisk.objects.all().update(goal_name="No goal set")


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0059_update_client_risk_goal_status_values"),
    ]

    operations = [migrations.RunPython(update_goal_name_to_goal, reverse_migration)]
