# Generated by Django 4.1.10 on 2025-06-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0058_client_hcr_type"),
        ("cbr_api", "0060_update_client_risk_goal_name_to_goal"),
    ]

    operations = []
