# Generated by Django 4.1.10 on 2025-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0061_merge_20250610_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrisk",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("INIT", "Initial"),
                    ("RL", "Risk Level Change"),
                    ("GS", "Goal Status Change"),
                    ("OTH", "Other"),
                ],
                default="INIT",
                max_length=5,
            ),
        ),
    ]
