# Generated by Django 4.1.10 on 2025-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0062_clientrisk_change_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clientrisk",
            index=models.Index(
                fields=["client_id", "risk_type", "timestamp"],
                name="cbr_api_cli_client__bef25f_idx",
            ),
        ),
    ]
