# Generated by Django 4.1.10 on 2025-06-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0063_clientrisk_cbr_api_cli_client__bef25f_idx"),
    ]

    operations = []
