# Generated by Django 4.1.10 on 2025-06-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0064_auto_20250612_1241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientrisk",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("INIT", "Initial"),
                    ("RL", "Risk Level Change"),
                    ("GS", "Goal Status Change"),
                    ("BOTH", "Both Risk Level and Goal Status Change"),
                    ("OTH", "Other"),
                ],
                default="INIT",
                max_length=5,
            ),
        ),
    ]
