# Generated by Django 4.1.10 on 2025-06-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0065_alter_clientrisk_change_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrisk",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
