# Generated by Django 4.1.10 on 2025-06-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0065_alter_clientrisk_change_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="educat_goal_status",
            field=models.CharField(
                choices=[
                    ("CAN", "Cancelled"),
                    ("GO", "Ongoing"),
                    ("CON", "Concluded"),
                    ("NS", "Not Set"),
                ],
                default="NS",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="health_goal_status",
            field=models.CharField(
                choices=[
                    ("CAN", "Cancelled"),
                    ("GO", "Ongoing"),
                    ("CON", "Concluded"),
                    ("NS", "Not Set"),
                ],
                default="NS",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="mental_goal_status",
            field=models.CharField(
                choices=[
                    ("CAN", "Cancelled"),
                    ("GO", "Ongoing"),
                    ("CON", "Concluded"),
                    ("NS", "Not Set"),
                ],
                default="NS",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="nutrit_goal_status",
            field=models.CharField(
                choices=[
                    ("CAN", "Cancelled"),
                    ("GO", "Ongoing"),
                    ("CON", "Concluded"),
                    ("NS", "Not Set"),
                ],
                default="NS",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="social_goal_status",
            field=models.CharField(
                choices=[
                    ("CAN", "Cancelled"),
                    ("GO", "Ongoing"),
                    ("CON", "Concluded"),
                    ("NS", "Not Set"),
                ],
                default="NS",
                max_length=3,
            ),
        ),
    ]
