# Generated by Django 4.1.10 on 2025-07-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cbr_api",
            "0066_client_educat_goal_status_client_health_goal_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="educat_goal_status",
        ),
        migrations.RemoveField(
            model_name="client",
            name="health_goal_status",
        ),
        migrations.RemoveField(
            model_name="client",
            name="mental_goal_status",
        ),
        migrations.RemoveField(
            model_name="client",
            name="nutrit_goal_status",
        ),
        migrations.RemoveField(
            model_name="client",
            name="social_goal_status",
        ),
        migrations.AlterField(
            model_name="client",
            name="educat_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="health_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="mental_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nutrit_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="social_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="clientrisk",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="LO",
                max_length=2,
            ),
        ),
    ]
