# Generated by Django 4.1.10 on 2025-07-04 21:16

from django.db import migrations
from cbr_api.models import RiskLevel, RiskType, GoalOutcomes

def update_client_risk_levels(apps, schema_editor):
    Client = apps.get_model('cbr_api', 'Client')
    ClientRisk = apps.get_model('cbr_api', 'ClientRisk')

    # Define which goal_statuses mean "active"
    ACTIVE_GOAL_STATUSES = [GoalOutcomes.ONGOING]
    INACTIVE_RISK_LEVEL = RiskLevel.NOT_ACTIVE

    risk_types_and_fields = [
        (RiskType.HEALTH, "health_risk_level"),
        (RiskType.SOCIAL, "social_risk_level"),
        (RiskType.EDUCAT, "educat_risk_level"),
        (RiskType.NUTRIT, "nutrit_risk_level"),
        (RiskType.MENTAL, "mental_risk_level"),
    ]

    for client in Client.objects.all():
        for risk_type, field in risk_types_and_fields:
            # Does this client have any active goal for this risk type?
            has_active_goal = ClientRisk.objects.filter(
                client_id=client.id,
                risk_type=risk_type,
                goal_status__in=ACTIVE_GOAL_STATUSES,
            ).exists()
            if not has_active_goal:
                setattr(client, field, INACTIVE_RISK_LEVEL)
        client.save()

class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0067_remove_client_educat_goal_status_and_more"),
    ]

    operations = [
        migrations.RunPython(update_client_risk_levels),
    ]
