# Generated by Django 4.1.10 on 2025-07-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0068_auto_20250704_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="educat_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="health_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="mental_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nutrit_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="social_risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="clientrisk",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("LO", "Low"),
                    ("ME", "Medium"),
                    ("HI", "High"),
                    ("CR", "Critical"),
                    ("NA", "Not Active"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
    ]
