# Generated by Django 4.1.10 on 2025-07-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0066_clientrisk_cancellation_reason"),
        ("cbr_api", "0069_alter_client_educat_risk_level_and_more"),
    ]

    operations = []
