# Generated by Django 4.1.10 on 2025-09-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0071_backfill_outcomes_into_improvements"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Outcome",
        ),
    ]
