# Generated by Django 4.1.10 on 2025-10-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0072_delete_outcome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientrisk",
            name="goal",
        ),
    ]
