# Generated by Django 4.1.10 on 2026-01-25 06:16

import cbr_api.models
import cbr_api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0074_add_impairment_disabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cbr_api.storage.OverwriteStorage(),
                upload_to=cbr_api.models.Visit.rename_file,
            ),
        ),
    ]
