# Generated by Django 4.1.10 on 2026-02-01 00:04

import cbr_api.util
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0074_add_impairment_disabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientNote",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("note", models.TextField()),
                (
                    "created_at",
                    models.BigIntegerField(default=cbr_api.util.current_milli_time),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="cbr_api.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patientnote",
            index=models.Index(
                fields=["client", "created_at"], name="cbr_api_pat_client__f2125a_idx"
            ),
        ),
    ]