# Generated by Django 4.1.10 on 2026-02-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0075_patientnote_and_more"),
    ]

    operations = []