# Generated by Django 4.1.10 on 2026-02-05 04:42

import cbr_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0076_align_patientnote_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientnote",
            name="id",
            field=models.CharField(
                default=cbr_api.models.generate_id,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
