# Generated by Django 4.1.10 on 2026-02-05 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0077_alter_patientnote_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientnote",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
