# Generated by Django 4.1.10 on 2026-02-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0076_email_settings_password_updated_at"),
        ("cbr_api", "0078_alter_patientnote_id"),
    ]

    operations = []
