# Generated by Django 4.1.10 on 2026-02-23 03:55


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0075_visit_picture"),
        ("cbr_api", "0079_merge_20260209_1702"),
    ]

    operations = []
