# Generated by Django 4.1.10 on 2026-07-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbr_api", "0091_successstory_multi_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="safe_guarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="referral",
            name="safe_guarding_action_needed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("URGENT_ATTENTION", "Urgent Attention"),
                    ("FOLLOW_UP", "Follow-up"),
                    ("DOCUMENTATION_ONLY", "Documentation Only"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="safe_guarding_observation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIGNS_OF_HARM", "Signs of Harm"),
                    ("NEGLECT", "Neglect"),
                    ("UNSAFE_BEHAVIOUR", "Unsafe Behaviour"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="safe_guarding_person_involved",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
