import { themeColors } from "@cbr/common";
import { StyleSheet } from "react-native";
import theme from "../../util/theme.styles";

const useStyles = () =>
    StyleSheet.create({
        clientButtons: {
            padding: 3,
            marginTop: 3,
            marginBottom: 15,
            width: 256,
            borderRadius: 5,
        },
        clientCardContainerStyles: {
            marginTop: 10,
            alignItems: "center",
            borderRadius: 20,
        },
        clientCardImageStyle: {
            width: 256,
            height: 256,
            marginTop: 10,
            marginBottom: 10,
            borderColor: "#273263",
            borderWidth: 10,
            borderBottomLeftRadius: 30,
            borderBottomRightRadius: 30,
            borderTopRightRadius: 30,
            borderTopLeftRadius: 30,
            overflow: "hidden",
        },

        clientDetailsContainerStyles: {
            marginTop: 20,
            marginBottom: 20,
            paddingBottom: 15,
            paddingTop: 15,
            alignItems: "center",
            borderRadius: 20,
        },
        clientTextStyle: {
            marginTop: 10,
            marginBottom: 10,
            height: 60,
            width: 350,
            borderBottomLeftRadius: 5,
            borderBottomRightRadius: 5,
            borderTopRightRadius: 5,
            borderTopLeftRadius: 5,
        },
        clientDetailsButtons: {
            alignItems: "center",
            padding: 3,
            marginTop: 5,
            marginBottom: 15,
            width: 350,
            borderRadius: 5,
        },
        carePresentView: {
            alignItems: "center",
            display: "flex",
            flexDirection: "row",
            height: 40,
            width: 350,
            marginTop: 15,
            marginBottom: 15,
        },
        carePresentCheckBox: {
            alignContent: "flex-start",
            fontSize: 18,
            width: 256,
            marginBottom: 15,
        },
        scrollViewStyles: {
            marginHorizontal: 5,
        },
        clientDetailsFinalButtons: {
            padding: 3,
            marginTop: 3,
            marginBottom: 15,
            marginLeft: 10,
            marginRight: 10,
            width: 112,
            borderRadius: 5,
        },
        disabilityButton: {
            justifyContent: "flex-start",
            width: 184,
        },
        clientBirthdayView: {
            display: "flex",
            alignItems: "flex-start",
            alignContent: "space-between",
            flexDirection: "row",
            justifyContent: "center",
            height: 40,
            width: 350,
            marginTop: 15,
            marginBottom: 15,
        },
        clientBirthdayButtons: {
            marginTop: 3,
            marginBottom: 15,
            marginRight: 15,
            width: 75,
            borderRadius: 5,
        },
        pickerStyle: {
            backgroundColor: "white",
            borderWidth: 1,
            borderColor: "blue",
            borderRadius: 5,
            alignItems: "center",
            paddingHorizontal: 8,
            paddingVertical: 8,
            marginHorizontal: 8,
            marginVertical: 8,
            height: 40,
            width: 200,
        },
        clientDetailsFinalView: {
            alignItems: "center",
            justifyContent: "flex-end",
            display: "flex",
            flexDirection: "row",
            height: 40,
            width: 350,
            marginTop: 15,
            marginBottom: 15,
        },
        riskCardStyle: {
            display: "flex",
            justifyContent: "space-between",
            marginTop: 20,
            marginBottom: 20,
            paddingBottom: 15,
            paddingTop: 15,
            alignItems: "center",
            borderRadius: 20,
        },
        riskCardContentStyle: {
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            height: 70,
            width: 350,
            marginTop: 15,
        },
        riskIconStyle: {
            marginTop: 10,
            display: "flex",
            justifyContent: "flex-start",
        },
        riskTitleStyle: {
            marginTop: 10,
            fontSize: 32,
            justifyContent: "center",
            fontWeight: "bold",
        },
        riskSubtitleStyle: {
            marginTop: 14,
            fontSize: 22,
            alignItems: "center",
            justifyContent: "flex-end",
            display: "flex",
            flexDirection: "row",
        },
        riskHeaderStyle: {
            marginTop: 14,
            marginBottom: 2,
            fontSize: 18,
            justifyContent: "flex-start",
            fontWeight: "bold",
        },
        riskRequirementStyle: {
            fontSize: 16,
            justifyContent: "flex-start",
        },
        cardSectionTitle: {
            textAlign: "center",
            marginTop: 14,
            marginBottom: 14,
            fontSize: 32,
        },
        activityCardContentStyle: {
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            height: 110,
            width: 350,
            marginTop: 15,
        },
        itemDividerStyle: {
            borderBottomColor: "black",
            borderBottomWidth: 1,
        },
        loadingContainer: {
            alignItems: "center",
            justifyContent: "center",
            flex: 1,
            marginTop: 300,
        },
        disabilityCheckContainer: {
            display: "flex",
            flex: 0,
        },
        disabilityListHeaderContainerStyle: {
            marginTop: 4,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 4,
        },
        disabilityListHeaderStyle: {
            fontSize: 24,
        },
        disabilityChecklist: {
            height: 500,
            marginHorizontal: 20,
            marginTop: 140,
            display: "flex",
            backgroundColor: "white",
            borderRadius: 10,
            justifyContent: "space-between",
        },
        zoneChecklist: {
            height: 540,
            marginHorizontal: 20,
            marginTop: 140,
            display: "flex",
            backgroundColor: "white",
            borderRadius: 10,
            justifyContent: "space-between",
        },
        nestedScrollView: {
            display: "flex",
            justifyContent: "center",
            padding: 20,
            height: 480,
        },
        nestedScrollStyle: {
            marginBottom: 10,
        },
        otherDisabilityStyle: {
            marginLeft: 5,
            marginEnd: 10,
            height: 60,
            width: 300,
            borderBottomLeftRadius: 5,
            borderBottomRightRadius: 5,
            borderTopRightRadius: 5,
            borderTopLeftRadius: 5,
        },
        modalSelectorButton: {
            padding: 3,
            marginLeft: 10,
            marginRight: 10,
            borderRadius: 5,
        },
        errorText: {
            color: themeColors.errorRed,
            alignSelf: "center",
        },
    });

export default useStyles;
