name: Debug Test Server
on:
  push:
    branches: [your-branch-name] # Only your branch
  workflow_dispatch: # Allows manual triggering

jobs:
  test-server:
    runs-on: [self-hosted, docker]
    container:
      image: python:3.9.1-buster
    timeout-minutes: 60
    services:
      test_postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_DB: cbr
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
    env:
      DOMAIN: example.com
      POSTGRES_DB: cbr
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: test_postgres
      SECRET_KEY: test
    steps:
      - name: Checkout server code into container
        uses: bfraser/cicd/actions/checkout@v1
        with:
          path: /isolated_build/repo/

      - name: Debug - Check network connectivity
        run: |
          echo "=== Network Debug Info ==="
          echo "Hostname: $(hostname)"
          echo "Checking if test_postgres resolves..."
          nslookup test_postgres || echo "nslookup failed"
          echo "Trying to ping test_postgres..."
          ping -c 3 test_postgres || echo "ping failed"
          echo "Checking if PostgreSQL port is open..."
          nc -zv test_postgres 5432 || echo "netcat failed"
          echo "=== End Network Debug ==="

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: /isolated_build/repo/server

      - name: Run Django Test Suite
        run: python manage.py test --verbosity=2 --no-input
        working-directory: /isolated_build/repo/server
